# Generated by Django 2.2.5 on 2020-03-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewFreelancer',
        ),
    ]
