# Generated by Django 2.2.5 on 2020-01-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='post_id',
        ),
    ]
