# Generated by Django 2.2.5 on 2020-01-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200108_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
