# Generated by Django 2.2.5 on 2020-01-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200108_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.TextField(max_length=40),
        ),
    ]
