# Generated by Django 2.2.5 on 2020-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200108_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.TextField(choices=[('1', 'Sürücü'), ('2', 'Kuryer'), ('3', 'Təmizlikçi'), ('4', 'Elektrik')]),
        ),
    ]
